/**
 * English Wikipedia article titles that differ from mledoze `name.common`.
 * Keyed by ISO3. Anything not listed here uses `name.common` verbatim.
 *
 * Titles are resolved at runtime with `redirects=1`, so a redirect (e.g.
 * "East Timor" → "Timor-Leste") still works; keeping the canonical title
 * here just saves a hop. Edit freely — this file is the single source of truth.
 */
export const WIKIPEDIA_TITLES = {
  ALA: 'Åland',
  ASM: 'American Samoa',
  ATA: 'Antarctica',
  ATF: 'French Southern and Antarctic Lands',
  BES: 'Caribbean Netherlands',
  BHS: 'The Bahamas',
  BLM: 'Saint Barthélemy',
  BVT: 'Bouvet Island',
  CCK: 'Cocos (Keeling) Islands',
  CIV: 'Ivory Coast',
  COD: 'Democratic Republic of the Congo',
  COG: 'Republic of the Congo',
  CPV: 'Cape Verde',
  CUW: 'Curaçao',
  CZE: 'Czech Republic',
  DMA: 'Dominica',
  DOM: 'Dominican Republic',
  ESH: 'Western Sahara',
  FSM: 'Federated States of Micronesia',
  GBR: 'United Kingdom',
  GEO: 'Georgia (country)',
  GGY: 'Guernsey',
  GMB: 'The Gambia',
  GNB: 'Guinea-Bissau',
  HKG: 'Hong Kong',
  HMD: 'Heard Island and McDonald Islands',
  IMN: 'Isle of Man',
  IOT: 'British Indian Ocean Territory',
  IRL: 'Republic of Ireland',
  JEY: 'Jersey',
  KOR: 'South Korea',
  MAC: 'Macau',
  MAF: 'Saint Martin (island)',
  MMR: 'Myanmar',
  NER: 'Niger',
  PCN: 'Pitcairn Islands',
  PRK: 'North Korea',
  PSE: 'State of Palestine',
  REU: 'Réunion',
  SGS: 'South Georgia and the South Sandwich Islands',
  SHN: 'Saint Helena, Ascension and Tristan da Cunha',
  SJM: 'Svalbard and Jan Mayen',
  STP: 'São Tomé and Príncipe',
  SWZ: 'Eswatini',
  SXM: 'Sint Maarten',
  TLS: 'East Timor',
  TUR: 'Turkey',
  TWN: 'Taiwan',
  UMI: 'United States Minor Outlying Islands',
  UNK: 'Kosovo',
  USA: 'United States',
  VAT: 'Vatican City',
  VGB: 'British Virgin Islands',
  VIR: 'United States Virgin Islands',
  WSM: 'Samoa',
};
